import networkx as nx
import json
import os
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

def build_learning_path(gap_with_scores: list, required_skills: list) -> dict:
    # Load courses
    courses_path = os.path.join(os.path.dirname(__file__), "courses.json")
    with open(courses_path, "r") as f:
        courses_catalog = json.load(f)

    # Build DAG
    G = nx.DiGraph()
    for course in courses_catalog:
        G.add_node(course["id"], **course)
        for prereq in course.get("prerequisites", []):
            G.add_edge(prereq, course["id"])

    # Select courses for gaps
    selected_course_ids = set()
    gap_skill_names = [g["skill"].lower() for g in gap_with_scores]
    
    for course in courses_catalog:
        course_skills = [s.lower() for s in course.get("skills_covered", [])]
        if any(skill in gap_skill_names for skill in course_skills):
            selected_course_ids.add(course["id"])
            # Add prerequisites recursively
            for prereq in nx.ancestors(G, course["id"]):
                selected_course_ids.add(prereq)

    # Subgraph and topological sort
    subgraph = G.subgraph(selected_course_ids)
    try:
        execution_order = list(nx.topological_sort(subgraph))
    except nx.NetworkXUnfeasible:
        execution_order = list(selected_course_ids)

    learning_path = [G.nodes[cid] for cid in execution_order]

    # Generate reasoning trace via Gemini
    reasoning_trace = "The learning path was generated by analyzing your skill gaps against the job description. " \
                      "We used a GRU-based knowledge tracer to estimate your mastery levels and a " \
                      "Directed Acyclic Graph (DAG) to ensure all prerequisites are met in the correct order."
    
    if os.getenv("GEMINI_API_KEY"):
        try:
            model = genai.GenerativeModel('gemini-1.5-flash')
            prompt = f"Explain why these courses were selected for a candidate missing these skills: {', '.join(gap_skill_names)}. Courses: {', '.join([c['title'] for c in learning_path])}. Keep it professional and encouraging."
            response = model.generate_content(prompt)
            reasoning_trace = response.text
        except:
            pass

    return {
        "learning_path": learning_path,
        "reasoning_trace": reasoning_trace
    }
